
INSERT INTO PERSON (ID, NAME, LOCATION,BIRTH_DATE) values(100001,'Vibha','Stockholm',CURRENT_TIMESTAMP());
INSERT INTO PERSON (ID, NAME, LOCATION,BIRTH_DATE) values(100002,'Rakesh','Stockholm',CURRENT_TIMESTAMP());
INSERT INTO PERSON (ID, NAME, LOCATION,BIRTH_DATE) values(100003,'Yaana','Stockholm',CURRENT_TIMESTAMP());
